//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Pete/Input System/InputHandler.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputHandler : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputHandler()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputHandler"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""829e7416-919b-4c1d-af89-4f045068756e"",
            ""actions"": [
                {
                    ""name"": ""Grapple Switch"",
                    ""type"": ""Button"",
                    ""id"": ""6c689b1b-bf46-495c-9d9a-354fd2a479d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grapple Release"",
                    ""type"": ""Button"",
                    ""id"": ""e065dc05-4bd1-4b79-b2d1-1143afcb780b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""59e214cf-aa86-43f1-a78e-b2d9a67ee410"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ab8367a2-9ba5-4a58-a32c-51b5bb5daab0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grapple Pull"",
                    ""type"": ""Button"",
                    ""id"": ""9bb6d427-a3a1-47f5-8ebf-5a8a5f8e0833"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause Game"",
                    ""type"": ""Button"",
                    ""id"": ""10810a43-77a0-479a-937e-59746fb1ae39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""219f795e-1e07-4249-abb8-0912b6fa90c9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Switch Mode"",
                    ""type"": ""Button"",
                    ""id"": ""1372210f-a333-48dd-8076-6df5d453fc7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeavyAttack"",
                    ""type"": ""Button"",
                    ""id"": ""a7a7501f-250d-4dc0-ba45-5c02fc46adfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightAttack"",
                    ""type"": ""Button"",
                    ""id"": ""f7fb2d2d-f7db-410d-9e23-f8fa2a8d1012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiUp"",
                    ""type"": ""Button"",
                    ""id"": ""24a71db0-cb8e-4c66-a963-45bfa06ff53c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiDown"",
                    ""type"": ""Button"",
                    ""id"": ""071cffc7-8be5-4f5f-9ab5-3784650a7044"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiLeft"",
                    ""type"": ""Button"",
                    ""id"": ""39ba4dad-216c-47dc-ad19-dae8d20caffa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiRight"",
                    ""type"": ""Button"",
                    ""id"": ""d4914d46-0c08-480e-879c-e95b028b6dad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiAction"",
                    ""type"": ""Button"",
                    ""id"": ""9efb7824-8d43-4d87-b463-25f751613ed5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadScene"",
                    ""type"": ""Button"",
                    ""id"": ""a3b6f74f-d35c-41c8-91e8-fee5dd2947bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackToMenu"",
                    ""type"": ""Button"",
                    ""id"": ""a0d8c0b9-cf24-4256-b664-67b507a93f7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueInput"",
                    ""type"": ""Button"",
                    ""id"": ""0ebe237e-d45a-4bc0-9359-c13ff129f95a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InfoScreen"",
                    ""type"": ""Button"",
                    ""id"": ""6295e6c3-61b3-4424-baa7-87f583ea638d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bc4dd424-7b15-4898-8348-2a5d18d0fb49"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43ff0014-8b63-4127-ac22-baac6a59d312"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d698645a-0db6-48c9-a5be-abc2f832dccf"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e58518f-480d-4d6b-88ac-b3759ae10a8b"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7da6ec1e-7ae3-41fa-8c70-4fc3a3da7b98"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2423efe-ebd2-4298-a9a8-3960ca5eed1b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e8b769b-8dfe-4f4c-993b-c52080959925"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""50ac7999-389e-4ef5-973c-60cb02dcc9d1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""76f8eb9e-a614-4c97-b0cc-6004d4e3d7a8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""40ed8c63-c2e3-4033-a90e-863c03660321"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""64b7b42e-811a-4394-a597-625b0737f0dc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ab8c093f-07c7-43e9-b4b5-52fa8027ea58"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c6551683-a54d-4d12-9515-888a4f553bb7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65cfb76e-2858-4bdb-a7b4-50c4deb25b3c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c591ae14-7422-4258-bb52-39482322c0dc"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8532e611-0f37-449b-bf87-195a5743f70c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03168051-8b0b-4cfa-98f2-77a6c22cf7ca"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause Game"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""171e4304-11d5-45de-a7eb-d850e507db30"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=15,y=15),StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f2493e-70b8-4116-a181-f40421d547ab"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe8e876b-27ae-4625-ade0-756e61f9619a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ebcf71-b5c1-41e8-8777-1a13ffd446f8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0313dcce-2fa2-494a-8098-1b94bd338c6b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b216fc7-180f-45b3-8e64-e5e4b63fdca4"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2443cb16-af80-4a7d-b5a2-c2c73e0aa541"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7b26978-2d58-41ce-a033-1eb719474b14"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dbc8853-eb59-435e-a936-89554731104b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccd49abb-8a34-4c56-b257-23a068f63c49"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d649f7f4-7fd2-4f54-9068-10696b3f6fc8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33914a71-cc5e-4958-b2fa-d7354e2b918d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86f892c8-63f4-4416-8ebe-67f51f40ef09"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e9d92bc-dc63-47a7-8585-f48b148bdb22"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab3a05eb-97c4-4c27-821a-27a265f02646"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c987626-323f-464b-96be-2fec1deadb58"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72442157-9fcd-4147-bea1-3d0dede4e82b"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e6bf5a2-a702-45f7-874c-94b301cadbc6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd964911-3b75-47fb-bf4f-22b94a818b7f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70fe4940-e8e2-49ee-9c68-f8a70fbb80b6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd176732-19ee-4c2d-8d4f-5fab94332922"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8c7fb1-78e8-435c-baa3-feecf4b57dba"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""483dc340-77a3-40a5-a9ed-34b469c99de6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b265658-8c36-4c47-a984-ed679c8e9da7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b5f62ea-051e-4ee1-a899-88168f07e2ad"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InfoScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb1f7d18-2dc4-4720-a00a-46d56e7761b1"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InfoScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_GrappleSwitch = m_Player.FindAction("Grapple Switch", throwIfNotFound: true);
        m_Player_GrappleRelease = m_Player.FindAction("Grapple Release", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_GrapplePull = m_Player.FindAction("Grapple Pull", throwIfNotFound: true);
        m_Player_PauseGame = m_Player.FindAction("Pause Game", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_SwitchMode = m_Player.FindAction("Switch Mode", throwIfNotFound: true);
        m_Player_HeavyAttack = m_Player.FindAction("HeavyAttack", throwIfNotFound: true);
        m_Player_LightAttack = m_Player.FindAction("LightAttack", throwIfNotFound: true);
        m_Player_GraffitiUp = m_Player.FindAction("GraffitiUp", throwIfNotFound: true);
        m_Player_GraffitiDown = m_Player.FindAction("GraffitiDown", throwIfNotFound: true);
        m_Player_GraffitiLeft = m_Player.FindAction("GraffitiLeft", throwIfNotFound: true);
        m_Player_GraffitiRight = m_Player.FindAction("GraffitiRight", throwIfNotFound: true);
        m_Player_GraffitiAction = m_Player.FindAction("GraffitiAction", throwIfNotFound: true);
        m_Player_ReloadScene = m_Player.FindAction("ReloadScene", throwIfNotFound: true);
        m_Player_BackToMenu = m_Player.FindAction("BackToMenu", throwIfNotFound: true);
        m_Player_DialogueInput = m_Player.FindAction("DialogueInput", throwIfNotFound: true);
        m_Player_InfoScreen = m_Player.FindAction("InfoScreen", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_GrappleSwitch;
    private readonly InputAction m_Player_GrappleRelease;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_GrapplePull;
    private readonly InputAction m_Player_PauseGame;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_SwitchMode;
    private readonly InputAction m_Player_HeavyAttack;
    private readonly InputAction m_Player_LightAttack;
    private readonly InputAction m_Player_GraffitiUp;
    private readonly InputAction m_Player_GraffitiDown;
    private readonly InputAction m_Player_GraffitiLeft;
    private readonly InputAction m_Player_GraffitiRight;
    private readonly InputAction m_Player_GraffitiAction;
    private readonly InputAction m_Player_ReloadScene;
    private readonly InputAction m_Player_BackToMenu;
    private readonly InputAction m_Player_DialogueInput;
    private readonly InputAction m_Player_InfoScreen;
    public struct PlayerActions
    {
        private @InputHandler m_Wrapper;
        public PlayerActions(@InputHandler wrapper) { m_Wrapper = wrapper; }
        public InputAction @GrappleSwitch => m_Wrapper.m_Player_GrappleSwitch;
        public InputAction @GrappleRelease => m_Wrapper.m_Player_GrappleRelease;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @GrapplePull => m_Wrapper.m_Player_GrapplePull;
        public InputAction @PauseGame => m_Wrapper.m_Player_PauseGame;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @SwitchMode => m_Wrapper.m_Player_SwitchMode;
        public InputAction @HeavyAttack => m_Wrapper.m_Player_HeavyAttack;
        public InputAction @LightAttack => m_Wrapper.m_Player_LightAttack;
        public InputAction @GraffitiUp => m_Wrapper.m_Player_GraffitiUp;
        public InputAction @GraffitiDown => m_Wrapper.m_Player_GraffitiDown;
        public InputAction @GraffitiLeft => m_Wrapper.m_Player_GraffitiLeft;
        public InputAction @GraffitiRight => m_Wrapper.m_Player_GraffitiRight;
        public InputAction @GraffitiAction => m_Wrapper.m_Player_GraffitiAction;
        public InputAction @ReloadScene => m_Wrapper.m_Player_ReloadScene;
        public InputAction @BackToMenu => m_Wrapper.m_Player_BackToMenu;
        public InputAction @DialogueInput => m_Wrapper.m_Player_DialogueInput;
        public InputAction @InfoScreen => m_Wrapper.m_Player_InfoScreen;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @GrappleSwitch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitch;
                @GrappleSwitch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitch;
                @GrappleSwitch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitch;
                @GrappleRelease.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleRelease;
                @GrappleRelease.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleRelease;
                @GrappleRelease.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleRelease;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @GrapplePull.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrapplePull;
                @GrapplePull.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrapplePull;
                @GrapplePull.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrapplePull;
                @PauseGame.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPauseGame;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @SwitchMode.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchMode;
                @SwitchMode.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchMode;
                @SwitchMode.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchMode;
                @HeavyAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeavyAttack;
                @HeavyAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeavyAttack;
                @HeavyAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeavyAttack;
                @LightAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLightAttack;
                @LightAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLightAttack;
                @LightAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLightAttack;
                @GraffitiUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiUp;
                @GraffitiUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiUp;
                @GraffitiUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiUp;
                @GraffitiDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiDown;
                @GraffitiDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiDown;
                @GraffitiDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiDown;
                @GraffitiLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiLeft;
                @GraffitiLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiLeft;
                @GraffitiLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiLeft;
                @GraffitiRight.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiRight;
                @GraffitiRight.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiRight;
                @GraffitiRight.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiRight;
                @GraffitiAction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiAction;
                @GraffitiAction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiAction;
                @GraffitiAction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiAction;
                @ReloadScene.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadScene;
                @ReloadScene.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadScene;
                @ReloadScene.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadScene;
                @BackToMenu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackToMenu;
                @BackToMenu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackToMenu;
                @BackToMenu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackToMenu;
                @DialogueInput.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDialogueInput;
                @DialogueInput.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDialogueInput;
                @DialogueInput.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDialogueInput;
                @InfoScreen.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInfoScreen;
                @InfoScreen.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInfoScreen;
                @InfoScreen.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInfoScreen;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GrappleSwitch.started += instance.OnGrappleSwitch;
                @GrappleSwitch.performed += instance.OnGrappleSwitch;
                @GrappleSwitch.canceled += instance.OnGrappleSwitch;
                @GrappleRelease.started += instance.OnGrappleRelease;
                @GrappleRelease.performed += instance.OnGrappleRelease;
                @GrappleRelease.canceled += instance.OnGrappleRelease;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @GrapplePull.started += instance.OnGrapplePull;
                @GrapplePull.performed += instance.OnGrapplePull;
                @GrapplePull.canceled += instance.OnGrapplePull;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @SwitchMode.started += instance.OnSwitchMode;
                @SwitchMode.performed += instance.OnSwitchMode;
                @SwitchMode.canceled += instance.OnSwitchMode;
                @HeavyAttack.started += instance.OnHeavyAttack;
                @HeavyAttack.performed += instance.OnHeavyAttack;
                @HeavyAttack.canceled += instance.OnHeavyAttack;
                @LightAttack.started += instance.OnLightAttack;
                @LightAttack.performed += instance.OnLightAttack;
                @LightAttack.canceled += instance.OnLightAttack;
                @GraffitiUp.started += instance.OnGraffitiUp;
                @GraffitiUp.performed += instance.OnGraffitiUp;
                @GraffitiUp.canceled += instance.OnGraffitiUp;
                @GraffitiDown.started += instance.OnGraffitiDown;
                @GraffitiDown.performed += instance.OnGraffitiDown;
                @GraffitiDown.canceled += instance.OnGraffitiDown;
                @GraffitiLeft.started += instance.OnGraffitiLeft;
                @GraffitiLeft.performed += instance.OnGraffitiLeft;
                @GraffitiLeft.canceled += instance.OnGraffitiLeft;
                @GraffitiRight.started += instance.OnGraffitiRight;
                @GraffitiRight.performed += instance.OnGraffitiRight;
                @GraffitiRight.canceled += instance.OnGraffitiRight;
                @GraffitiAction.started += instance.OnGraffitiAction;
                @GraffitiAction.performed += instance.OnGraffitiAction;
                @GraffitiAction.canceled += instance.OnGraffitiAction;
                @ReloadScene.started += instance.OnReloadScene;
                @ReloadScene.performed += instance.OnReloadScene;
                @ReloadScene.canceled += instance.OnReloadScene;
                @BackToMenu.started += instance.OnBackToMenu;
                @BackToMenu.performed += instance.OnBackToMenu;
                @BackToMenu.canceled += instance.OnBackToMenu;
                @DialogueInput.started += instance.OnDialogueInput;
                @DialogueInput.performed += instance.OnDialogueInput;
                @DialogueInput.canceled += instance.OnDialogueInput;
                @InfoScreen.started += instance.OnInfoScreen;
                @InfoScreen.performed += instance.OnInfoScreen;
                @InfoScreen.canceled += instance.OnInfoScreen;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnGrappleSwitch(InputAction.CallbackContext context);
        void OnGrappleRelease(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnGrapplePull(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSwitchMode(InputAction.CallbackContext context);
        void OnHeavyAttack(InputAction.CallbackContext context);
        void OnLightAttack(InputAction.CallbackContext context);
        void OnGraffitiUp(InputAction.CallbackContext context);
        void OnGraffitiDown(InputAction.CallbackContext context);
        void OnGraffitiLeft(InputAction.CallbackContext context);
        void OnGraffitiRight(InputAction.CallbackContext context);
        void OnGraffitiAction(InputAction.CallbackContext context);
        void OnReloadScene(InputAction.CallbackContext context);
        void OnBackToMenu(InputAction.CallbackContext context);
        void OnDialogueInput(InputAction.CallbackContext context);
        void OnInfoScreen(InputAction.CallbackContext context);
    }
}
