//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Pete/Input System/InputHandler.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputHandler : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputHandler()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputHandler"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""829e7416-919b-4c1d-af89-4f045068756e"",
            ""actions"": [
                {
                    ""name"": ""Grapple Switch"",
                    ""type"": ""Button"",
                    ""id"": ""6c689b1b-bf46-495c-9d9a-354fd2a479d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrappleSwitch(Back)"",
                    ""type"": ""Button"",
                    ""id"": ""7a5e25c5-f50a-43e4-86d9-d4bacc1b14b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grapple Release"",
                    ""type"": ""Button"",
                    ""id"": ""e065dc05-4bd1-4b79-b2d1-1143afcb780b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""59e214cf-aa86-43f1-a78e-b2d9a67ee410"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ab8367a2-9ba5-4a58-a32c-51b5bb5daab0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grapple Pull"",
                    ""type"": ""Button"",
                    ""id"": ""9bb6d427-a3a1-47f5-8ebf-5a8a5f8e0833"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""219f795e-1e07-4249-abb8-0912b6fa90c9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Switch Mode"",
                    ""type"": ""Button"",
                    ""id"": ""1372210f-a333-48dd-8076-6df5d453fc7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeavyAttack"",
                    ""type"": ""Button"",
                    ""id"": ""a7a7501f-250d-4dc0-ba45-5c02fc46adfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightAttack"",
                    ""type"": ""Button"",
                    ""id"": ""f7fb2d2d-f7db-410d-9e23-f8fa2a8d1012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiUp"",
                    ""type"": ""Button"",
                    ""id"": ""24a71db0-cb8e-4c66-a963-45bfa06ff53c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiDown"",
                    ""type"": ""Button"",
                    ""id"": ""071cffc7-8be5-4f5f-9ab5-3784650a7044"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiLeft"",
                    ""type"": ""Button"",
                    ""id"": ""39ba4dad-216c-47dc-ad19-dae8d20caffa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiRight"",
                    ""type"": ""Button"",
                    ""id"": ""d4914d46-0c08-480e-879c-e95b028b6dad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GraffitiAction"",
                    ""type"": ""Button"",
                    ""id"": ""9efb7824-8d43-4d87-b463-25f751613ed5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadScene"",
                    ""type"": ""Button"",
                    ""id"": ""a3b6f74f-d35c-41c8-91e8-fee5dd2947bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackToMenu"",
                    ""type"": ""Button"",
                    ""id"": ""a0d8c0b9-cf24-4256-b664-67b507a93f7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueInput"",
                    ""type"": ""Button"",
                    ""id"": ""0ebe237e-d45a-4bc0-9359-c13ff129f95a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NoAimGrapple"",
                    ""type"": ""Button"",
                    ""id"": ""5aac3e22-7a16-47de-adce-2f18cb2942d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScrollY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8a08253a-2764-47ac-96ce-8efaf769c32b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""9483b822-e0e3-4a0a-82e1-bcc52d77b365"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipCutscene"",
                    ""type"": ""Button"",
                    ""id"": ""fdc74d54-569f-4908-ac64-a6a6566720bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3620209-fe2e-4db6-9884-851fc47977ac"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b402023-dc68-4c68-8c35-67298b3877e7"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Switch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d698645a-0db6-48c9-a5be-abc2f832dccf"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e58518f-480d-4d6b-88ac-b3759ae10a8b"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Release"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7da6ec1e-7ae3-41fa-8c70-4fc3a3da7b98"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2423efe-ebd2-4298-a9a8-3960ca5eed1b"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""50ac7999-389e-4ef5-973c-60cb02dcc9d1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""76f8eb9e-a614-4c97-b0cc-6004d4e3d7a8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""40ed8c63-c2e3-4033-a90e-863c03660321"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""64b7b42e-811a-4394-a597-625b0737f0dc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ab8c093f-07c7-43e9-b4b5-52fa8027ea58"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6e8b769b-8dfe-4f4c-993b-c52080959925"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6551683-a54d-4d12-9515-888a4f553bb7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65cfb76e-2858-4bdb-a7b4-50c4deb25b3c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c591ae14-7422-4258-bb52-39482322c0dc"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""171e4304-11d5-45de-a7eb-d850e507db30"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=15,y=15),StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe8e876b-27ae-4625-ade0-756e61f9619a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1f2493e-70b8-4116-a181-f40421d547ab"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switch Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0313dcce-2fa2-494a-8098-1b94bd338c6b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ebcf71-b5c1-41e8-8777-1a13ffd446f8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2443cb16-af80-4a7d-b5a2-c2c73e0aa541"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b216fc7-180f-45b3-8e64-e5e4b63fdca4"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dbc8853-eb59-435e-a936-89554731104b"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7b26978-2d58-41ce-a033-1eb719474b14"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d649f7f4-7fd2-4f54-9068-10696b3f6fc8"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccd49abb-8a34-4c56-b257-23a068f63c49"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86f892c8-63f4-4416-8ebe-67f51f40ef09"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33914a71-cc5e-4958-b2fa-d7354e2b918d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab3a05eb-97c4-4c27-821a-27a265f02646"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e9d92bc-dc63-47a7-8585-f48b148bdb22"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c987626-323f-464b-96be-2fec1deadb58"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GraffitiAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72442157-9fcd-4147-bea1-3d0dede4e82b"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e6bf5a2-a702-45f7-874c-94b301cadbc6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd964911-3b75-47fb-bf4f-22b94a818b7f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70fe4940-e8e2-49ee-9c68-f8a70fbb80b6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd176732-19ee-4c2d-8d4f-5fab94332922"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8c7fb1-78e8-435c-baa3-feecf4b57dba"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""483dc340-77a3-40a5-a9ed-34b469c99de6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b265658-8c36-4c47-a984-ed679c8e9da7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93b3e7f5-679e-4e9d-a24e-d1ad0f085da4"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrappleSwitch(Back)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b62391d1-6879-4615-9237-f9bbc6a29fb9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoAimGrapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c108397-483d-4634-9826-5fab7a3bb3cc"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoAimGrapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f6a0678-e9ce-4d3c-b33a-f66bc446dbc5"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScrollY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a5985df-dfc0-45af-9868-b775504fdfe6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e3f9bef-5caa-4b32-b054-a7a0c1965c10"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""820e267c-2129-4ef0-a4af-d1a954cba587"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipCutscene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d11fc26e-0f39-4c63-9e2b-98ae8cd33cb2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipCutscene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menus"",
            ""id"": ""c39e0ed4-3e44-425a-9015-2ba12145ee14"",
            ""actions"": [
                {
                    ""name"": ""InfoTabNext"",
                    ""type"": ""Button"",
                    ""id"": ""fbdc4705-5182-4539-ba3b-42892b2214a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InfoTabPrevious"",
                    ""type"": ""Button"",
                    ""id"": ""387c6c04-6021-4e9f-a8a6-302490209290"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenCloseInfo"",
                    ""type"": ""Button"",
                    ""id"": ""af254975-b088-41a1-bdba-d9c5b3626870"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackButton"",
                    ""type"": ""Button"",
                    ""id"": ""884f6d24-b154-4091-8028-09286a30af99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""70a01562-7c57-4bbd-b8ad-afd89407599b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MissionsTabNext"",
                    ""type"": ""Button"",
                    ""id"": ""a1b3ee69-5ee7-49f0-8664-103e70ebdfd4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MissionsTabPrevious"",
                    ""type"": ""Button"",
                    ""id"": ""87d087a2-176c-42d6-8a32-b9e3ed8a2fdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""eee00ed5-1b5b-4767-9af6-dfcac9bd8807"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InfoTabNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64688362-95d5-450e-a5a1-d962b8a0c50a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InfoTabPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a4584c-5fdb-4dd7-8b51-8f0aee3cea98"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCloseInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28193168-1dea-4c14-b1f2-e407327f2b53"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenCloseInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e1ce248-fb90-4ae2-a7e6-7cb4be2685f2"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62b87dbe-24c8-4a3c-9ba8-e0d78ee6720d"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27ad0099-e784-46c6-8008-6468d07859ec"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e70e07c8-463c-4516-9a3e-065d2732a6ae"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MissionsTabNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed5f15d0-b211-49eb-9fb8-253fcee2cd45"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MissionsTabPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_GrappleSwitch = m_Player.FindAction("Grapple Switch", throwIfNotFound: true);
        m_Player_GrappleSwitchBack = m_Player.FindAction("GrappleSwitch(Back)", throwIfNotFound: true);
        m_Player_GrappleRelease = m_Player.FindAction("Grapple Release", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_GrapplePull = m_Player.FindAction("Grapple Pull", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_SwitchMode = m_Player.FindAction("Switch Mode", throwIfNotFound: true);
        m_Player_HeavyAttack = m_Player.FindAction("HeavyAttack", throwIfNotFound: true);
        m_Player_LightAttack = m_Player.FindAction("LightAttack", throwIfNotFound: true);
        m_Player_GraffitiUp = m_Player.FindAction("GraffitiUp", throwIfNotFound: true);
        m_Player_GraffitiDown = m_Player.FindAction("GraffitiDown", throwIfNotFound: true);
        m_Player_GraffitiLeft = m_Player.FindAction("GraffitiLeft", throwIfNotFound: true);
        m_Player_GraffitiRight = m_Player.FindAction("GraffitiRight", throwIfNotFound: true);
        m_Player_GraffitiAction = m_Player.FindAction("GraffitiAction", throwIfNotFound: true);
        m_Player_ReloadScene = m_Player.FindAction("ReloadScene", throwIfNotFound: true);
        m_Player_BackToMenu = m_Player.FindAction("BackToMenu", throwIfNotFound: true);
        m_Player_DialogueInput = m_Player.FindAction("DialogueInput", throwIfNotFound: true);
        m_Player_NoAimGrapple = m_Player.FindAction("NoAimGrapple", throwIfNotFound: true);
        m_Player_MouseScrollY = m_Player.FindAction("MouseScrollY", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_SkipCutscene = m_Player.FindAction("SkipCutscene", throwIfNotFound: true);
        // Menus
        m_Menus = asset.FindActionMap("Menus", throwIfNotFound: true);
        m_Menus_InfoTabNext = m_Menus.FindAction("InfoTabNext", throwIfNotFound: true);
        m_Menus_InfoTabPrevious = m_Menus.FindAction("InfoTabPrevious", throwIfNotFound: true);
        m_Menus_OpenCloseInfo = m_Menus.FindAction("OpenCloseInfo", throwIfNotFound: true);
        m_Menus_BackButton = m_Menus.FindAction("BackButton", throwIfNotFound: true);
        m_Menus_PauseGame = m_Menus.FindAction("PauseGame", throwIfNotFound: true);
        m_Menus_MissionsTabNext = m_Menus.FindAction("MissionsTabNext", throwIfNotFound: true);
        m_Menus_MissionsTabPrevious = m_Menus.FindAction("MissionsTabPrevious", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_GrappleSwitch;
    private readonly InputAction m_Player_GrappleSwitchBack;
    private readonly InputAction m_Player_GrappleRelease;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_GrapplePull;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_SwitchMode;
    private readonly InputAction m_Player_HeavyAttack;
    private readonly InputAction m_Player_LightAttack;
    private readonly InputAction m_Player_GraffitiUp;
    private readonly InputAction m_Player_GraffitiDown;
    private readonly InputAction m_Player_GraffitiLeft;
    private readonly InputAction m_Player_GraffitiRight;
    private readonly InputAction m_Player_GraffitiAction;
    private readonly InputAction m_Player_ReloadScene;
    private readonly InputAction m_Player_BackToMenu;
    private readonly InputAction m_Player_DialogueInput;
    private readonly InputAction m_Player_NoAimGrapple;
    private readonly InputAction m_Player_MouseScrollY;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_SkipCutscene;
    public struct PlayerActions
    {
        private @InputHandler m_Wrapper;
        public PlayerActions(@InputHandler wrapper) { m_Wrapper = wrapper; }
        public InputAction @GrappleSwitch => m_Wrapper.m_Player_GrappleSwitch;
        public InputAction @GrappleSwitchBack => m_Wrapper.m_Player_GrappleSwitchBack;
        public InputAction @GrappleRelease => m_Wrapper.m_Player_GrappleRelease;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @GrapplePull => m_Wrapper.m_Player_GrapplePull;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @SwitchMode => m_Wrapper.m_Player_SwitchMode;
        public InputAction @HeavyAttack => m_Wrapper.m_Player_HeavyAttack;
        public InputAction @LightAttack => m_Wrapper.m_Player_LightAttack;
        public InputAction @GraffitiUp => m_Wrapper.m_Player_GraffitiUp;
        public InputAction @GraffitiDown => m_Wrapper.m_Player_GraffitiDown;
        public InputAction @GraffitiLeft => m_Wrapper.m_Player_GraffitiLeft;
        public InputAction @GraffitiRight => m_Wrapper.m_Player_GraffitiRight;
        public InputAction @GraffitiAction => m_Wrapper.m_Player_GraffitiAction;
        public InputAction @ReloadScene => m_Wrapper.m_Player_ReloadScene;
        public InputAction @BackToMenu => m_Wrapper.m_Player_BackToMenu;
        public InputAction @DialogueInput => m_Wrapper.m_Player_DialogueInput;
        public InputAction @NoAimGrapple => m_Wrapper.m_Player_NoAimGrapple;
        public InputAction @MouseScrollY => m_Wrapper.m_Player_MouseScrollY;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @SkipCutscene => m_Wrapper.m_Player_SkipCutscene;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @GrappleSwitch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitch;
                @GrappleSwitch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitch;
                @GrappleSwitch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitch;
                @GrappleSwitchBack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitchBack;
                @GrappleSwitchBack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitchBack;
                @GrappleSwitchBack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleSwitchBack;
                @GrappleRelease.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleRelease;
                @GrappleRelease.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleRelease;
                @GrappleRelease.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrappleRelease;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @GrapplePull.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrapplePull;
                @GrapplePull.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrapplePull;
                @GrapplePull.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGrapplePull;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @SwitchMode.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchMode;
                @SwitchMode.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchMode;
                @SwitchMode.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchMode;
                @HeavyAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeavyAttack;
                @HeavyAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeavyAttack;
                @HeavyAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHeavyAttack;
                @LightAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLightAttack;
                @LightAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLightAttack;
                @LightAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLightAttack;
                @GraffitiUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiUp;
                @GraffitiUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiUp;
                @GraffitiUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiUp;
                @GraffitiDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiDown;
                @GraffitiDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiDown;
                @GraffitiDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiDown;
                @GraffitiLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiLeft;
                @GraffitiLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiLeft;
                @GraffitiLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiLeft;
                @GraffitiRight.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiRight;
                @GraffitiRight.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiRight;
                @GraffitiRight.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiRight;
                @GraffitiAction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiAction;
                @GraffitiAction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiAction;
                @GraffitiAction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGraffitiAction;
                @ReloadScene.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadScene;
                @ReloadScene.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadScene;
                @ReloadScene.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnReloadScene;
                @BackToMenu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackToMenu;
                @BackToMenu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackToMenu;
                @BackToMenu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBackToMenu;
                @DialogueInput.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDialogueInput;
                @DialogueInput.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDialogueInput;
                @DialogueInput.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDialogueInput;
                @NoAimGrapple.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNoAimGrapple;
                @NoAimGrapple.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNoAimGrapple;
                @NoAimGrapple.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNoAimGrapple;
                @MouseScrollY.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseScrollY;
                @MouseScrollY.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseScrollY;
                @MouseScrollY.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseScrollY;
                @Interact.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @SkipCutscene.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkipCutscene;
                @SkipCutscene.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkipCutscene;
                @SkipCutscene.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkipCutscene;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GrappleSwitch.started += instance.OnGrappleSwitch;
                @GrappleSwitch.performed += instance.OnGrappleSwitch;
                @GrappleSwitch.canceled += instance.OnGrappleSwitch;
                @GrappleSwitchBack.started += instance.OnGrappleSwitchBack;
                @GrappleSwitchBack.performed += instance.OnGrappleSwitchBack;
                @GrappleSwitchBack.canceled += instance.OnGrappleSwitchBack;
                @GrappleRelease.started += instance.OnGrappleRelease;
                @GrappleRelease.performed += instance.OnGrappleRelease;
                @GrappleRelease.canceled += instance.OnGrappleRelease;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @GrapplePull.started += instance.OnGrapplePull;
                @GrapplePull.performed += instance.OnGrapplePull;
                @GrapplePull.canceled += instance.OnGrapplePull;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @SwitchMode.started += instance.OnSwitchMode;
                @SwitchMode.performed += instance.OnSwitchMode;
                @SwitchMode.canceled += instance.OnSwitchMode;
                @HeavyAttack.started += instance.OnHeavyAttack;
                @HeavyAttack.performed += instance.OnHeavyAttack;
                @HeavyAttack.canceled += instance.OnHeavyAttack;
                @LightAttack.started += instance.OnLightAttack;
                @LightAttack.performed += instance.OnLightAttack;
                @LightAttack.canceled += instance.OnLightAttack;
                @GraffitiUp.started += instance.OnGraffitiUp;
                @GraffitiUp.performed += instance.OnGraffitiUp;
                @GraffitiUp.canceled += instance.OnGraffitiUp;
                @GraffitiDown.started += instance.OnGraffitiDown;
                @GraffitiDown.performed += instance.OnGraffitiDown;
                @GraffitiDown.canceled += instance.OnGraffitiDown;
                @GraffitiLeft.started += instance.OnGraffitiLeft;
                @GraffitiLeft.performed += instance.OnGraffitiLeft;
                @GraffitiLeft.canceled += instance.OnGraffitiLeft;
                @GraffitiRight.started += instance.OnGraffitiRight;
                @GraffitiRight.performed += instance.OnGraffitiRight;
                @GraffitiRight.canceled += instance.OnGraffitiRight;
                @GraffitiAction.started += instance.OnGraffitiAction;
                @GraffitiAction.performed += instance.OnGraffitiAction;
                @GraffitiAction.canceled += instance.OnGraffitiAction;
                @ReloadScene.started += instance.OnReloadScene;
                @ReloadScene.performed += instance.OnReloadScene;
                @ReloadScene.canceled += instance.OnReloadScene;
                @BackToMenu.started += instance.OnBackToMenu;
                @BackToMenu.performed += instance.OnBackToMenu;
                @BackToMenu.canceled += instance.OnBackToMenu;
                @DialogueInput.started += instance.OnDialogueInput;
                @DialogueInput.performed += instance.OnDialogueInput;
                @DialogueInput.canceled += instance.OnDialogueInput;
                @NoAimGrapple.started += instance.OnNoAimGrapple;
                @NoAimGrapple.performed += instance.OnNoAimGrapple;
                @NoAimGrapple.canceled += instance.OnNoAimGrapple;
                @MouseScrollY.started += instance.OnMouseScrollY;
                @MouseScrollY.performed += instance.OnMouseScrollY;
                @MouseScrollY.canceled += instance.OnMouseScrollY;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @SkipCutscene.started += instance.OnSkipCutscene;
                @SkipCutscene.performed += instance.OnSkipCutscene;
                @SkipCutscene.canceled += instance.OnSkipCutscene;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Menus
    private readonly InputActionMap m_Menus;
    private IMenusActions m_MenusActionsCallbackInterface;
    private readonly InputAction m_Menus_InfoTabNext;
    private readonly InputAction m_Menus_InfoTabPrevious;
    private readonly InputAction m_Menus_OpenCloseInfo;
    private readonly InputAction m_Menus_BackButton;
    private readonly InputAction m_Menus_PauseGame;
    private readonly InputAction m_Menus_MissionsTabNext;
    private readonly InputAction m_Menus_MissionsTabPrevious;
    public struct MenusActions
    {
        private @InputHandler m_Wrapper;
        public MenusActions(@InputHandler wrapper) { m_Wrapper = wrapper; }
        public InputAction @InfoTabNext => m_Wrapper.m_Menus_InfoTabNext;
        public InputAction @InfoTabPrevious => m_Wrapper.m_Menus_InfoTabPrevious;
        public InputAction @OpenCloseInfo => m_Wrapper.m_Menus_OpenCloseInfo;
        public InputAction @BackButton => m_Wrapper.m_Menus_BackButton;
        public InputAction @PauseGame => m_Wrapper.m_Menus_PauseGame;
        public InputAction @MissionsTabNext => m_Wrapper.m_Menus_MissionsTabNext;
        public InputAction @MissionsTabPrevious => m_Wrapper.m_Menus_MissionsTabPrevious;
        public InputActionMap Get() { return m_Wrapper.m_Menus; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenusActions set) { return set.Get(); }
        public void SetCallbacks(IMenusActions instance)
        {
            if (m_Wrapper.m_MenusActionsCallbackInterface != null)
            {
                @InfoTabNext.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnInfoTabNext;
                @InfoTabNext.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnInfoTabNext;
                @InfoTabNext.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnInfoTabNext;
                @InfoTabPrevious.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnInfoTabPrevious;
                @InfoTabPrevious.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnInfoTabPrevious;
                @InfoTabPrevious.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnInfoTabPrevious;
                @OpenCloseInfo.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnOpenCloseInfo;
                @OpenCloseInfo.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnOpenCloseInfo;
                @OpenCloseInfo.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnOpenCloseInfo;
                @BackButton.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnBackButton;
                @BackButton.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnBackButton;
                @BackButton.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnBackButton;
                @PauseGame.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnPauseGame;
                @MissionsTabNext.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnMissionsTabNext;
                @MissionsTabNext.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnMissionsTabNext;
                @MissionsTabNext.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnMissionsTabNext;
                @MissionsTabPrevious.started -= m_Wrapper.m_MenusActionsCallbackInterface.OnMissionsTabPrevious;
                @MissionsTabPrevious.performed -= m_Wrapper.m_MenusActionsCallbackInterface.OnMissionsTabPrevious;
                @MissionsTabPrevious.canceled -= m_Wrapper.m_MenusActionsCallbackInterface.OnMissionsTabPrevious;
            }
            m_Wrapper.m_MenusActionsCallbackInterface = instance;
            if (instance != null)
            {
                @InfoTabNext.started += instance.OnInfoTabNext;
                @InfoTabNext.performed += instance.OnInfoTabNext;
                @InfoTabNext.canceled += instance.OnInfoTabNext;
                @InfoTabPrevious.started += instance.OnInfoTabPrevious;
                @InfoTabPrevious.performed += instance.OnInfoTabPrevious;
                @InfoTabPrevious.canceled += instance.OnInfoTabPrevious;
                @OpenCloseInfo.started += instance.OnOpenCloseInfo;
                @OpenCloseInfo.performed += instance.OnOpenCloseInfo;
                @OpenCloseInfo.canceled += instance.OnOpenCloseInfo;
                @BackButton.started += instance.OnBackButton;
                @BackButton.performed += instance.OnBackButton;
                @BackButton.canceled += instance.OnBackButton;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @MissionsTabNext.started += instance.OnMissionsTabNext;
                @MissionsTabNext.performed += instance.OnMissionsTabNext;
                @MissionsTabNext.canceled += instance.OnMissionsTabNext;
                @MissionsTabPrevious.started += instance.OnMissionsTabPrevious;
                @MissionsTabPrevious.performed += instance.OnMissionsTabPrevious;
                @MissionsTabPrevious.canceled += instance.OnMissionsTabPrevious;
            }
        }
    }
    public MenusActions @Menus => new MenusActions(this);
    public interface IPlayerActions
    {
        void OnGrappleSwitch(InputAction.CallbackContext context);
        void OnGrappleSwitchBack(InputAction.CallbackContext context);
        void OnGrappleRelease(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnGrapplePull(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSwitchMode(InputAction.CallbackContext context);
        void OnHeavyAttack(InputAction.CallbackContext context);
        void OnLightAttack(InputAction.CallbackContext context);
        void OnGraffitiUp(InputAction.CallbackContext context);
        void OnGraffitiDown(InputAction.CallbackContext context);
        void OnGraffitiLeft(InputAction.CallbackContext context);
        void OnGraffitiRight(InputAction.CallbackContext context);
        void OnGraffitiAction(InputAction.CallbackContext context);
        void OnReloadScene(InputAction.CallbackContext context);
        void OnBackToMenu(InputAction.CallbackContext context);
        void OnDialogueInput(InputAction.CallbackContext context);
        void OnNoAimGrapple(InputAction.CallbackContext context);
        void OnMouseScrollY(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSkipCutscene(InputAction.CallbackContext context);
    }
    public interface IMenusActions
    {
        void OnInfoTabNext(InputAction.CallbackContext context);
        void OnInfoTabPrevious(InputAction.CallbackContext context);
        void OnOpenCloseInfo(InputAction.CallbackContext context);
        void OnBackButton(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnMissionsTabNext(InputAction.CallbackContext context);
        void OnMissionsTabPrevious(InputAction.CallbackContext context);
    }
}
